spring:
  datasource:
    username: grizzle
    password: grizzle-1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/grizzle?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=PST&useSSL=false&characterEncoding=UTF-8
  jpa:
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
logging:
  level:
    org.springframework: info
    org.hibernate: off
server:
  port: 8082
words:
  reverse: grizzle-core/src/main/resources/mxm_reverse_mapping.txt
